---
# This role installs and sets up keepalived

- name: Install keepalived (Centos)
  yum: name=keepalived state=present
  when: ansible_os_family == "RedHat"
  tags: keepalived
  notify: restart keepalived

- name: Install keepalived (debian/ubuntu)
  apt: name=keepalived state=latest
  when: ansible_os_family == "Debian"
  tags: keepalived
  notify: restart keepalived

- name: chk_service script shell
  template: 
    src: "{{ local_script_path }}"
    dest: /etc/keepalived/check_zabbix.sh
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  notify: restart keepalived

- name: Configure keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=started
  tags: keepalived


